### ISSUE TITLE
Apply "named-parameters-function" Solhint rule

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-periphery#150]
Context:

- #143
- https://github.com/solhint-community/solhint-community/pull/25

**Comment by smol-ninja** [comment]
Since we decided to remove `solhint-community` in https://github.com/sablier-labs/v2-periphery/commit/f975c096d157d7a5bbdf2bbe1e2efb6daff0d45a, should we close this issue since `named-parameters-function` rule does not exist in `solhint`?

**Comment by smol-ninja** [comment]
Bumping this up to follow up on my previous comment.
