### ISSUE TITLE
Accept standard ERC-20 approvals in "ProxyTarget"

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-periphery#158]
## Problem

One of the biggest pain points of using Permit2 with Safe is that [all signatories need to sign the permit in a round-robin process](https://twitter.com/PaulRBerg/status/1686395627372949505).

We had a call with Utopia today to discuss a potential integration, and they said that this is one of the biggest issues with our current periphery setup.

## Solution

[Allow the periphery to be used via standard ERC-20 approvals](https://twitter.com/PaulRBerg/status/1686458086528008211).

## Proposal

We either:

1. Extend the current `ProxyTarget` to accept standard ERC-20 approvals
2. Turn the current `ProxyTarget` into an abstract with shared logic, and build two other `ProxyTargetPermit2` and `ProxyTargetERC20` to implement the Permit2 and ERC-20 variants.

**Comment by PaulRBerg** [comment]
In https://github.com/sablier-labs/v2-interfaces/discussions/380#discussioncomment-6628777, @razgraf said this:

> Not to mention updates like https://github.com/sablier-labs/v2-periphery/issues/158 which are already set to make the client app more complex (through more conditional branching), thus more error prone

What does this issue (accepting standard ERC-20 approvals) have to do with the Sablier Interface?

Our official app can continue to work with Permit2 exclusively. The point is to enable more flexibility for integrators like Utopia.

**Comment by razgraf** [comment]
Wouldn't our UI suffer from the same problem within the Safe integration? I was thinking we'd support both: Permit2 for cheap approvals, classic approve for async approvals.

**Comment by PaulRBerg** [comment]
Aah, good point ...

I wonder if it wouldn't be easier to let users toggle the approval mechanism?

**Comment by razgraf** [comment]
Yup, that's how I was thinking we should implement it. A global toggle. 

The default value could be permit2 for all deployments, for consistency, or we can make erc20-approve be the default jus for SAFEs. But that's a separate point.

**Comment by PaulRBerg** [comment]
Alternatively .. make ERC-20 the default and fuggetabout Permit2 🙈

Don't see much of an improvement in UX with Permit2, TBH, even for EOAs.
