### ISSUE TITLE
Simplify mappings in airstream factory

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-periphery#162]
The nested mappings here are overkill:

https://github.com/sablier-labs/v2-periphery/blob/eb65a2862bd75fd856723d8293b0c8018352f88d/src/SablierV2AirstreamFactory.sol#L23-L41

- It's bad UX to have to provide so many inputs to query a user's campaigns
- There's no benefit in splitting the campaigns by type, i.e., `LockupLinear` and `LockupDynamic`. Users are interested in all of their airstream campaigns; the payment type is a low-level detail.
- There's no point in storing the campaign details (expiration, Merkle tree) in the factory. What @razgraf suggested on the call was to emit these data in an event, not store them.
- Should there be a need to obtain the campaign's details (expiration, Merkle tree) those can be queried from the subgraph or the `Airstream` contract itself.
- Should there be a need for advanced filtering, the subgraph can help with that.

Given the feedback above, the solution is to rewrite the mappings like this:

```solidity
mapping(address user => ISablierV2Airstream[] contracts) internal _airstreams;
```

Let's please use `internal` over `private`. It would make testing easier.

Further corollaries:

- There's no point in blocking users from creating similar campaigns, i.e., we can remove the `CampaignAlreadyDeployed` error and the associated checks in the `createAirstream` functions. The same Merkle tree can be used for multiple airdrops.
- We can remove the `getAirstreamLockupDynamic` and `getAirstreamLockupLinear` getters, and replace them with a new getter `getAirstreams`, which returns all of the user's airstream campaigns.

**Comment by andreivladbrg** [comment]
I agree with most of your points. The idea behind these mappings was to create an open question. This question was written before our call, when Razvan made the suggestion:
https://github.com/sablier-labs/v2-periphery/blob/eb65a2862bd75fd856723d8293b0c8018352f88d/src/SablierV2AirstreamFactory.sol#L21-L22

And I've made it intentionally to look like 'overkill.

> Let's please use internal over private. It would make testing easier.

Why would this affect anything on the testing side?

> ``` mapping(address user => ISablierV2Airstream[] contracts) internal _airstreams;```

I think this would work.

> There's no point in blocking users from creating similar campaigns

Creating similar campaigns is really hard and pointless. The idea behind the revert was to prevent any potential spam.

**Comment by PaulRBerg** [comment]
Great, thanks @andreivladbrg.

> Why would this affect anything on the testing side?

Dunno, but I would rather not do the refactor later.

> to prevent any potential spam

Gas costs provide a natural defense against this.

> And I've made it intentionally to look like 'overkill.

Ah, ok, sorry!

> Should we have a `getAirstreams` and a `getAirstream(uint index)` function?

- `getAirstreams`: yes
- `getAirstream(uint256 index)`: don't think it would be that useful

**Comment by razgraf** [comment]
> Can you, please, name again here all the data to emit in the event when a campaign is created?

Sure: campaign `id`, `asset` and the following which will be sent as parameters to the create method: IPFS `CID`, expected `totalAmount` and expected number or `recipients`. These should be all the mandatory ones.

**Comment by PaulRBerg** [comment]
Thanks, @razgraf. The only trouble is that we don't have a campaign `id` at the moment 😅

We could do it like this:

```solidity
mapping(uint256 id => ISablierV2AirstreamCampaign campaign) internal _campaigns;
mapping(address user => ISablierV2AirstreamCampaign[] campaigns) internal _campaignsByUser;
```

The `user` could alternatively be named `admin`.

**Comment by razgraf** [comment]
Ah sorry, my bad, no identifier needed.
I'll be using the address of the instance itself as the identifier on my end when indexing + give it a subgraph generated id. No need to pollute the contract's state with it.
