### ISSUE TITLE
Update branching trees to use "given" keyword

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-periphery#167]
References:

- https://github.com/sablier-labs/v2-core/issues/621
- https://github.com/sablier-labs/v2-core/discussions/647
- https://github.com/sablier-labs/v2-core/pull/642

**Comment by smol-ninja** [comment]
Can you assign this to me? I can work on this.

**Comment by andreivladbrg** [comment]
Thanks for the interest, I just finished working on this branch: https://github.com/sablier-labs/v2-periphery/tree/test/improve-tree-wording. Was about to create a PR.
