### ISSUE TITLE
Contract for batch creating streams without proxy

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-periphery#168]
## Problem

As discussed [here](https://github.com/sablier-labs/v2-interfaces/discussions/380#discussioncomment-6768799), it is not possible to abstract away the proxy deployment in the UI because the proxy owner is an immutable variable in PRBProxy:

https://github.com/PaulRBerg/prb-proxy/blob/84ae9671d64023c0c21316392e11e33a2eaa2511/src/PRBProxy.sol#L27

Immutable variables don't exist during construction, so any attempt to read the owner when using `deployAndExecute` will revert.

## Solution

Implement a contract that can batch-create streams without relying on the proxy.

**Comment by andreivladbrg** [comment]
Given that we fixed the proxy abstraction with `SablierV2ProxyTargetPush`, can we close this issue? @PaulRBerg

**Comment by andreivladbrg** [comment]
Ok, should it be a push system or a classic pull?

**Comment by PaulRBerg** [comment]
It has to be a classic pull because the batch contract would be the same contract for all users. The push model works only when the user is in control of the contract (as is the case with PRBProxies).

The license: `GPL-3.0-or-later`.

**Comment by andreivladbrg** [comment]
> The push model works only when the user is in control of the contract

Yeah, wanted to make sure in case I was missing something out.

**Comment by andreivladbrg** [comment]
I currently did the following implementation: https://github.com/sablier-labs/v2-periphery/tree/feat/batch-create

I feel the naming might be a bit repetitive(contract + functions). Especially when:

https://github.com/sablier-labs/v2-periphery/blob/ec58ee142ed2650e063e76b5fee89b7d865fdee9/test/integration/batch-create/batch-create-with-durations/batchCreateWithDurations.t.sol#L41

I was thinking of renaming all function in `SablierV2BatchCreate` like this but I think it would be misleading:
  - `batchCreateWithDeltas` -> `createWithDeltas` 
  - `batchCreateWithDurations` -> `createWithDurations` 
  -  `batchCreateWithMilestones` -> `createWithMilestones`  
  - `batchCreateWithRange` -> `batchCreateWithRange`
  
@PaulRBerg What do you think? Should we keep it as it is, or do you have better suggestions?

**Comment by PaulRBerg** [comment]
`SablierV2Batch` is cool.

And removing the `batch` prefix from all those functions is cool, too.
