### ISSUE TITLE
Incorrect type returned by "getMerkleStreamers"

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-periphery#185]
The type returned by `getMerkleStreamers` should be `ISablierV2MerkleStreamer ` instead of `ISablierV2MerkleStreamer LL`:

https://github.com/sablier-labs/v2-periphery/blob/f8a14edb11cac2e0467f543d0a706dcc7d0010f6/src/SablierV2MerkleStreamerFactory.sol#L26-L34

**Comment by PaulRBerg** [comment]
@andreivladbrg could you pick up this task, please?

**Comment by andreivladbrg** [comment]
Yep 👍

**Comment by andreivladbrg** [comment]
Shouldn't we also change the `_merkleStreamers` mapping ?

https://github.com/sablier-labs/v2-periphery/blob/f8a14edb11cac2e0467f543d0a706dcc7d0010f6/src/SablierV2MerkleStreamerFactory.sol#L20

**Comment by PaulRBerg** [comment]
Yep, we should.
