### ISSUE TITLE
Adapt leaf hashing algorithm for MerkleStreamer

### ISSUE THREAD

**Issue by razgraf** [sablier-labs/v2-periphery#204]
In the MerkleStreamer campaign contract we use the following algorithm to construct our leaf:

1. we tightly encode three values (index, address, amount)
2. we create a keccak hash over them

https://github.com/sablier-labs/v2-periphery/blob/4b27ec08637514719b21a7780832bfd0d41b1c84/src/SablierV2MerkleStreamerLL.sol#L78

This is consistent with Uniswap's [approach](https://github.com/Uniswap/merkle-distributor/blob/25a79e8ec8c22076a735b1a675b961c8184e7931/contracts/MerkleDistributor.sol#L47), which unfortunately does not look like standard OpenZeppelin as far as leaf construction goes. 

As we had to replicate this algorithm outside of the contract (Javascript and Rust) we've bumped into some issues related to this choice:
1. `abi.encodePacked` is [harder](https://github.com/ethers-io/ethers.js/issues/718) (and less safe) to reproduce than `abi.encode`
2. the usage of a single keccak seems to go against security practices such as the ones against [second preimage attacks](https://flawed.net.nz/2018/02/21/attacking-merkle-trees-with-a-second-preimage-attack/)
3. all OpenZeppelin utilities, including the [JS library](https://github.com/OpenZeppelin/merkle-tree/#validating-a-proof-in-solidity) and the [Rust crate](https://lib.rs/crates/merkle-tree-rs) use `encode` and 2x `keccak` which makes compatibility not only a good argument for us but for external integrators as well 

---

@andreivladbrg @gavriliumircea and I are currently testing a version of our Merkle Streamer periphery with the following structure for generating leafs:
```solidity
bytes32 leaf = keccak256(bytes.concat(keccak256(abi.encode(index, recipient, amount))));
```

If successful, we propose swapping this algorithm in the `main` branch, inside the `claim` method.

**Comment by PaulRBerg** [comment]
Great idea and write-up. It seems like the right approach to switch to `abi.encode` and hash twice instead of just once.
