### ISSUE TITLE
Support cliffs in MerkleStreamerLL

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-periphery#247]
We have received this feature request from a potential airstream user.

**Comment by andreivladbrg** [comment]
Is this still an issue? We've decided that we have cliffs for the airstreams created when `claim` is called

**Comment by PaulRBerg** [comment]
No, it isn't!

As discussed on the call yesterday, this was a mistake on my part. I have forgotten that the `MerkleStreamer` contract has support for cliffs. It's just that the UI hasn't implemented it.

> And if one wants to have a cliff for the campaign it selft, the admin can simply don't fund it.

Indeed.
