### ISSUE TITLE
Integrate Slither for continuous static analysis

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-periphery#260]
Replicate this workflow:

https://github.com/sablier-labs/v2-core/blob/main/.github/workflows/ci-slither.yml

**Comment by PaulRBerg** [comment]
Let's keep it open

**Comment by smol-ninja** [comment]
Should I close it now as its no more needed because of package tethering PR?

**Comment by PaulRBerg** [comment]
Yep
