### ISSUE TITLE
Refactor all tests to use Bulloak

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-periphery#265]
See:

- https://github.com/alexfertel/bulloak
- https://prberg.com/presentations/solidity-summit-2023

**Comment by smol-ninja** [comment]
Should it be a part of V2.2?

**Comment by PaulRBerg** [comment]
Nope, it shouldn't

**Comment by smol-ninja** [comment]
Duplicate of https://github.com/sablier-labs/v2-core/issues/799
