### ISSUE TITLE
Allow `leafData` length to be 1 in merkle lockup fork tests

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-periphery#266]

**Comment by smol-ninja** [comment]
Why is there a requirement to have a test for 1 stream? Meanwhile, by removing [`vm.assume(params.leafData.length > 1);`](https://github.com/sablier-labs/v2-periphery/blob/18d08400fa75194ac48c016e7913064eb63c32b1/test/fork/merkle-lockup/MerkleLL.t.sol#L61C26-L61C34), the fork tests can have 1 recipient as input (i.e. 1 stream).

**Comment by PaulRBerg** [comment]
> Why is there a requirement to have a test for 1 stream?

This is what tests are meant for, right?

Completeness + thoroughness

**Comment by smol-ninja** [comment]
Yes it does. I was just curious if there is a specific reason because the number of recipients are only fuzzed in the fork tests where $n > 1$. So instead of writing a separate test for 1 stream, why not let n be 1 in fork test. Its also complete that way.

**Comment by PaulRBerg** [comment]
Oh, I see. Yeah, let's just allow n b e 1 in the fork tests.

**Comment by smol-ninja** [comment]
Resolved by https://github.com/sablier-labs/v2-core/pull/979/commits/b65f89dfe9ff9449cb766f03113f6f235bd74bfd.
