### ISSUE TITLE
Package tethering

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-periphery#269]
Related: https://github.com/sablier-labs/v2-core/issues/808 and https://github.com/sablier-labs/company-discussions/discussions/25

The task is to move all contracts in this repository to the `v2-lockup` repository (formerly known as `v2-core`)

**Comment by smol-ninja** [comment]
Resolved with https://github.com/sablier-labs/v2-core/pull/979 and https://github.com/sablier-labs/v2-core/pull/994
