### ISSUE TITLE
Replace `computeCreate2Address` (deprecated) with `vm.computeCreate2Address`

### ISSUE THREAD

**Issue by smol-ninja** [sablier-labs/v2-periphery#327]
<img width="855" alt="Screenshot 2024-04-12 at 14 49 53" src="https://github.com/sablier-labs/v2-periphery/assets/6676622/5200e0f9-af72-4c08-aaaa-c920f48ed7fd">

**Comment by ThreeHrSleep** [comment]
can take this on :)
