### ISSUE TITLE
A view function to verify the sum of percentages in MLT prior to deployment

### ISSUE THREAD

**Issue by smol-ninja** [sablier-labs/v2-periphery#356]
As discussed [here](https://github.com/sablier-labs/v2-periphery/issues/353#issuecomment-2178060522), the goal is to write a view function that verifies that the sum of percentages of tranches equals 100%. 

```solidity
/// @notice Verifies if the sum of percentages in `tranches` equals 100% , i.e. 1e18.
/// @dev Reverts if the sum of percentages overflows.
/// @param tranches The tranches with their respective unlock percentages.
/// @return result True if the sum of percentages equals 100%, otherwise false.
function isPercentagesSum100(MerkleLT.TrancheWithPercentage[] calldata tranches)
    external
    pure
    returns (bool result);
```

**Comment by PaulRBerg** [comment]
Is this utility that much helpful, @razgraf? Don't JS big numbers solve this?

I'm generally wary of adding onchain logic for frontend-only purposes.

cc @razgraf

**Comment by razgraf** [comment]
Our system will of course make sure the calculations are done right, but there's always a very small chance of getting 99.9999999 instead of 100. Given we don't revert any more, I simply suggested we add an extra layer of checks. It would act in stead of that missing revert - which will be useful for us, but also for **integrators** bumping into this same precision problem (e.g. usually happens with uneven division like 5 days with 3 steps/tranches).

**Comment by andreivladbrg** [comment]
I have an idea, since we still have the loop in create factory function:

https://github.com/sablier-labs/v2-periphery/blob/46ca3bc1253057d9fefa0646e5d48d01d0319375/src/SablierV2MerkleLockupFactory.sol#L69-L75

why not move this logic into a separate function:

```solidity
```

**Comment by smol-ninja** [comment]
@andreivladbrg Its not that piece, but [this piece](https://github.com/sablier-labs/v2-periphery/blob/46ca3bc1253057d9fefa0646e5d48d01d0319375/src/SablierV2MerkleLT.sol#L56-L61) that.

```solidity
        // Calculate the total percentage of the tranches and save them in the contract state.
        uint64 totalPercentage;
        for (uint256 i = 0; i < tranchesWithPercentages.length; ++i) {
            uint64 percentage = tranchesWithPercentages[i].unlockPercentage.unwrap();
            totalPercentage += percentage;
            _tranchesWithPercentages.push(tranchesWithPercentages[i]);
        }
        TOTAL_PERCENTAGE = totalPercentage;
```

**Comment by smol-ninja** [comment]
What is your final vote on this @PaulRBerg? I find @razgraf's argument convincing.

**Comment by andreivladbrg** [comment]
I am also of the opinion that we can add the function

**Comment by PaulRBerg** [comment]
OK I changed my mind, happy to add this utility function. Good point about integrators @razgraf.

> there's always a very small chance of getting 99.9999999 instead of 100

This is unlikely to happen with non-floating-point big numbers.

Other errors are more likely, e.g. a tranche percentage not included in the final array delivered to the contract.
