### ISSUE TITLE
Remove `CancelMultiple` struct from Batch Lockup library

### ISSUE THREAD

**Issue by smol-ninja** [sablier-labs/v2-periphery#373]
Its redundant.

https://github.com/sablier-labs/v2-periphery/blob/ab9dfdd5501749aa5efa3a90bb5d9b91707dd247/src/types/DataTypes.sol#L10-L14

**Comment by MukulKolpe** [comment]
Hey @smol-ninja, can I work on this issue?

**Comment by smol-ninja** [comment]
Hi @MukulKolpe. Yes you can. Please make sure to create the PR against the `staging` branch. And thank you very much for helping us out with this.

**Comment by MukulKolpe** [comment]
Hi @smol-ninja, thanks. I have raised a PR against the `staging` branch.

**Comment by smol-ninja** [comment]
Thank you. I will review it later.
